# Generated by Django 3.0.4 on 2020-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
