# Generated by Django 3.0.4 on 2020-03-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200318_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.URLField(blank=True, max_length=250, unique=True),
        ),
    ]
